/**
 * @file    prv_uart.h
 * @brief   APIs for UART modules.
 * @version 0.1
 * @date    2023-06-29
 *
 * @copyright Copyright (c) 2023
 *
 */

#ifndef _PRV_UART_H_
#define _PRV_UART_H_

#include "prv_gpio.h"

#define URT0 ((URT_REG_t *)_URT0_)
#define URT1 ((URT_REG_t *)_URT1_)

/* Macro to Start URT0 transmit */
#define URT0_START_TRANSMIT() (URT0CON |= _URT0CON_TXEN_MASK)

/* Macro to Start URT1 transmit */
#define URT1_START_TRANSMIT() (URT1CON |= _URT1CON_TXEN_MASK)

/* Macro to Stop URT0 transmit */
#define URT0_STOP_TRANSMIT() (URT0CON &= ~_URT0CON_TXEN_MASK)

/* Macro to Stop URT1 transmit */
#define URT1_STOP_TRANSMIT() (URT1CON &= ~_URT1CON_TXEN_MASK)

/* Macro to Start URT0 receive */
#define URT0_START_RECEIVE() (URT0CON |= _URT0CON_RXEN_MASK)

/* Macro to Start URT1 receive */
#define URT1_START_RECEIVE() (URT1CON |= _URT1CON_RXEN_MASK)

/* Macro to Stop URT0 receive */
#define URT0_STOP_RECEIVE() (URT0CON &= ~_URT0CON_RXEN_MASK)

/* Macro to Stop URT1 receive */
#define URT1_STOP_RECEIVE() (URT1CON &= ~_URT1CON_RXEN_MASK)

/* Macro to get the correct value for the baud rate */
#define UART_BAUD_RATE(_bdrate) ((((SYSCLK / IOCLKDIV) / (_bdrate * 2))) - 1)

/* Defines Uart buffer Read errors */
typedef enum
{
    UART_BUFF_STATUS_NOERR = 0,
    UART_BUFF_STATUS_BUFFER_FULL,
    UART_BUFF_STATUS_BUFFER_EMPTY
} UART_BUFF_STATUS_t;

/* Defines Errors generated by Uart Modules */
typedef enum
{
    UART_STATUS_NOERR = 0,
    UART_STATUS_BUFFER_FULL,
	UART_STATUS_BUFFER_EMPTY,
    UART_STATUS_PARITY_ERR,
} UART_STATUS_t;

/* Defines Parity options */
typedef enum
{
    UART_PARITY_EVEN = 0,
    UART_PARITY_ODD,
} UART_PARITY_t;

/* Structure defining the buffer */
typedef struct
{
    uint8_t *dataBuffer;
    volatile uint32_t buffHead;
    volatile uint32_t buffTail;
    uint32_t buffMask;
} BUFF_CONFIG_t;

/* Structure defining configuration of Uart Module */
typedef struct
{
    uint32_t baud_rate;
    bool enbit9;
    UART_PARITY_t parity;
    uint32_t rxpin;
    uint32_t txpin;
    BUFF_CONFIG_t buff_cfg;
    UART_STATUS_t error;
} UART_CONFIG_t;

/*************************************************************/
/* *** Mapped to Hardware *** */

/* Structure defining Uart registers - mapped to the hardware */
typedef struct
{
    _IO_ uint32_t URTCON;
    _IO_ uint32_t URTBRG;
    _IO_ uint32_t TX;
    _IO_ uint32_t RX;
} URT_REG_t;

/*************************************************************/

/**
 * @brief API to Initialize Uart Module.
 * 
 * @param module Constant pointer to UART modules to access hardwre registers. Pass URT0 or URT1 as module parameter.
 * @param config Uart Configurations. Use UART_CONFIG_t structure to set the required configurations.
 */
void UART_Initialize(URT_REG_t *const module, UART_CONFIG_t *config);

/**
 * @brief API to Read data from Uart rx buffer. returns status of the read.
 * 
 * @param dest                Pointer to the location to copy the data in the rx buffer.
 * @param config              Uart Configurations. Use UART_CONFIG_t structure to set the required configurations.
 * @return UART_BUFF_STATUS_t Status of the operation. Refer to enum UART_BUFF_STATUS_t.
 */
UART_BUFF_STATUS_t UART_readByte(uint8_t *dest, UART_CONFIG_t *config);

/**
 * @brief API to check the if data is available in the rx buffer.
 * 
 * @param config Uart Configurations. Use UART_CONFIG_t structure to set the required configurations.
 * @return true  If data is present in rx buffer.
 * @return false If rx buffer is empty.
 */
bool UART_isAvailable(UART_CONFIG_t *config);

/**
 * @brief API to clear rx buffer - resets the buffer index to 0 and buffer status.
 * 
 * @param config Uart Configurations. Use UART_CONFIG_t structure to set the required configurations.
 */
void UART_bufferFlush(UART_CONFIG_t *config);

/**
 * @brief API to push a Byte into the Uart circular buffer.
 *
 * @param buff_cfg            Pointer to buffer configuration structure. Use BUFF_CONFIG_t structure to set the required configurations.
 * @param data                Byte to be pushed into the buffer.
 * @return UART_BUFF_STATUS_t Status of the buffer after the operation. Refer to enum UART_BUFF_STATUS_t.
 */
UART_BUFF_STATUS_t push_buffer(BUFF_CONFIG_t *buff_cfg, uint8_t data);

/**
 * @brief API to pop a Byte from the Uart circular buffer.
 *
 * @param buff_cfg            Pointer to buffer configuration structure. Use BUFF_CONFIG_t structure to set the required configurations.
 * @param data                Pointer to the location where the Byte would be stored after the pop operation.
 * @return UART_BUFF_STATUS_t Status of the buffer after the operation. Refer to enum UART_BUFF_STATUS_t.
 */
UART_BUFF_STATUS_t pop_buffer(BUFF_CONFIG_t *buff_cfg, uint8_t *data);

/**
 * @brief API to Transmit UART data - blocking, polls TXIF flag.
 * 
 * @param module Constant pointer to UART modules to access hardwre registers. Pass URT0 or URT1 as module parameter.
 * @param data   Character to send.
 * @param config Uart Configurations. Use UART_CONFIG_t structure to set the required configurations.
 */
void UART_TXBlocking(URT_REG_t *const module, uint8_t data, const UART_CONFIG_t *const config);

/**
 * @brief API to Receive UART data - non blocking. This API must be called inside an Interrupt Handler.
 *        The data received is stored in the data buffer pointed by rx_dataBuffer.
 * 
 * @param module Constant pointer to UART modules to access hardwre registers. Pass URT0 or URT1 as module parameter.
 * @param config Uart Configurations. Use UART_CONFIG_t structure to set the required configurations.
 */
void UART_RXnonBlocking(URT_REG_t *const module, UART_CONFIG_t *config);

#endif /* _PRV_UART_H_ */
